# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 04:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0004_auto_20161125_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='id',
        ),
        migrations.AlterField(
            model_name='albums',
            name='copyrightdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 25, 4, 29, 59, 501919, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='songs',
            name='songTitle',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
