# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0010_auto_20161128_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='copyrightdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 28, 16, 43, 24, 167548, tzinfo=utc)),
        ),
    ]
