# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dbApp', '0003_auto_20161125_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('addressPhone', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('albumId', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('albumTitle', models.CharField(max_length=50)),
                ('copyrightdate', models.DateField(default=datetime.datetime(2016, 11, 25, 4, 26, 30, 381874, tzinfo=utc))),
                ('speed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AppearsOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Albums')),
            ],
        ),
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('instrumentId', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('instrumentName', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('ssn', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Performs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Musicians')),
            ],
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Instruments')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Musicians')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songTitle', models.CharField(max_length=50)),
                ('songWriter', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='performs',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Songs'),
        ),
        migrations.AddField(
            model_name='appearson',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Songs'),
        ),
        migrations.AddField(
            model_name='albums',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Musicians'),
        ),
    ]
