# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0005_auto_20161125_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='songId',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='albums',
            name='copyrightdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 26, 17, 59, 45, 242400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='albums',
            name='speed',
            field=models.IntegerField(choices=[(33, 33), (45, 45), (78, 78)], default=45),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='key',
            field=models.CharField(choices=[('Ab', 'A Flat'), ('A', 'A'), ('A#', 'A Sharp'), ('Bb', 'B Flat'), ('B', 'B'), ('C', 'C'), ('C#', 'C Sharp'), ('Db', 'D Flat'), ('D', 'D'), ('D#', 'D Sharp'), ('Eb', 'E Flat'), ('E', 'E'), ('F', 'F'), ('F#', 'F Sharp'), ('Gb', 'G Flat'), ('G', 'G'), ('G#', 'G Sharp')], default='B Flat', max_length=2),
        ),
        migrations.AlterField(
            model_name='musicians',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='songs',
            name='songTitle',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='songs',
            name='songWriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbApp.Musicians'),
        ),
    ]
