# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 03:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0007_auto_20161127_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='copyrightdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 27, 3, 48, 43, 694163, tzinfo=utc)),
        ),
    ]
