# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbApp', '0009_auto_20161128_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='copyrightdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 28, 9, 18, 51, 273476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
